#This is the automated build part of the CI/CD pipeline. Documentation on problems experienced can be found 
#in the Documentation folder in BuildStageTrouble.md
on: 
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: ./src
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Fix flutter SDK folder permission
      run: git config --global --add safe.directory /tmp/flutter/--
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: ‘stable’

    - name: install dependencies
      run: flutter pub get

    - name: Run Tests
      run: flutter test

    - name: Flutter Build
      run: flutter build web 
    #should it not be 




