#This is the automated build part of the CI/CD pipeline. Documentation on problems experienced can be found 
#in the Documentation folder in BuildStageTrouble.md
on: 
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-jammy
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        channel: ‘stable’

    - name: install dependencies
      working-directory: ./src
      run: flutter pub get
    - name: Run Tests
      working-directory: ./src
      run: flutter test

    - name: Flutter Build
      working-directory: ./src
      run: flutter build web 
    #should it not be 




