name: CSC325 Flutter App Deploy

on:
  workflow_call:

jobs:
  deploy:
    steps:
      - name: Deploy
        working-directory: ./.github/workflows
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/build/web/